### ISSUE TITLE
Fibonacci series

### ISSUE THREAD

**Issue by milantenk** [norabalogh/python-tdd-training#3]
I would like to have a function that is able to calculate the first "n" elements of the Fibonacci series.

**Comment by milantenk** [comment]
Tests added on commit e8c03651a33c4627eb35e60461709a354da3e458

**Comment by milantenk** [comment]
Please create a pull request if you are done. :)

**Comment by noratenk** [comment]
Please write a test for negative inputs.

**Comment by milantenk** [comment]
#4

**Comment by milantenk** [comment]
Done
